cdxj-indexer path
sul-dlss/was_robot_suite pull request #469
Opened 2022-06-13 22:32 UTC by edsu

## Why was this change made? 🤔

Hard code the full path to where pip3 installs cdxj-indexer in the was
user's home directory. Available via `Settings.cdxj_indexer.bin`.

## How was this change tested? 🤨

Unit tests.

⚡ ⚠ If this change involves consuming from other services or writing to shared file systems, test that web archive seed and crawl accessioning works properly in [stage|qa] environment, in addition to specs. ⚡

2022-06-13 22:34 UTC, jcoyne requested changes
In the description, you restated what you did, but not why it was necessary. Can you expand that?

2022-06-13 22:39 UTC, edsu commented
@jcoyne sure, I added a bit more context from the referenced ticket.

2022-06-13 22:55 UTC, mjgiarlo approved these changes

2022-06-14 00:38 UTC, jcoyne approved these changes

2022-06-14 12:46 UTC, merged