Create structural metadata using cocina
sul-dlss/was_robot_suite pull request #674
Opened 2024-03-20 16:54 UTC by jcoyne

Ref #654

## Why was this change made? 🤔

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from other services or writing to shared file systems, test that web archive seed and crawl accessioning works properly in [stage|qa] environment, in addition to specs. ⚡

2024-03-20 20:29 UTC, justinlittman requested changes

2024-03-20 20:29 UTC, justinlittman commented on lib/dor/was_seed/structural_builder.rb
> +      # @param [Array<Array<Assembly::ObjectFile>>] objects the list of files to add to structural metadata
Isn't there always only a single ObjectFile? Seems like this has additional complexity to support an array.

2024-03-20 20:29 UTC, justinlittman commented on lib/dor/was_seed/structural_builder.rb
> +      # @param [String] reading_order ('left-to-right') only valid for books, can be 'right-to-left' or 'left-to-right'.
reading_order is cruft?

2024-03-20 20:29 UTC, justinlittman commented on lib/dor/was_seed/structural_builder.rb
> +        structural[:hasMemberOrders] = [{ viewingDirection: reading_order }] if cocina_model.type == Cocina::Models::ObjectType.book
cruft?

2024-03-20 20:29 UTC, justinlittman commented on lib/dor/was_seed/structural_builder.rb
> +      def self.administrative(file_attributes, object_access)
Can't administrative just be hardcoded for the single file?

2024-03-20 20:29 UTC, justinlittman commented on lib/dor/was_seed/structural_builder.rb
> +        filesets.map.with_index(1) do |fileset, sequence| # iterate over all the resources
There's only ever one fileset.

2024-03-20 20:30 UTC, justinlittman commented
This seems excessively complex for the structural for a single file.

2024-03-21 01:44 UTC, jcoyne commented
This was copied from common-accessioning. We can make it simpler, but this approach is tried and tested.

2024-03-21 12:09 UTC, justinlittman commented
In GIS Robot Suite it is only as complicated as it needs to be: https://github.com/sul-dlss/gis-robot-suite/blob/main/lib/robots/dor_repo/gis_assembly/generate_structural.rb

2024-03-26 11:17 UTC, justinlittman approved these changes

2024-03-26 11:17 UTC, justinlittman commented
Holding for testing by @andrewjbtw

2024-03-26 20:30 UTC, merged